### ISSUE TITLE
Unable to build boiler-writter solution in Visual Studio

### ISSUE THREAD

**Issue by i-vivdich** [akiver/boiler-writter#1]
Hi. I've followed instructions on how to build the solution. Particularly, followed steps in 'Common tasks' section and first two steps in Windows build section. However, when I open boiler-writter solution in VS and try to Debug it, next errors show up: 
"'Steam_RunCallbacks': identifier not found at boiler-writter-master\boiler-writter\main.cpp",
"'GetHSSteamPipe': identifier not found at boiler-writter-master\boiler-writter\main.cpp",
"'GetHSSteamPipe': identifier not found at boiler-writter-master\boiler-writter\CSGOCLient.cpp".

Could you please hint me what is the problem or what is the solution? I would be very grateful for any info on these problems.

**Comment by akiver** [comment]
Hi,

It looks like the Steamworks API changed, I will look into it.
In the meantime, you should download the **v1.46** from the downloads page https://partner.steamgames.com/downloads/list, it should work fine with this version.

**Comment by akiver** [comment]
I pushed a fix, it should work now with the last Steamworks SDK

**Comment by i-vivdich** [comment]
OK, thanks for collaboration.
