### ISSUE TITLE
how should this program work?

### ISSUE THREAD

**Issue by PetroGolovnya** [akiver/boiler-writter#2]
Hi!

I build this code (patched version) in VS 2013  with SDK version 1.48a and run boiler.exe  some times in console under Windows Server 2012 R2:
boiler.exe "c:\temp" 3412362507493310638 3412368466760433761 13730

![изображение](https://user-images.githubusercontent.com/25701171/81524647-2c7f7600-937c-11ea-8c73-03a92b086e25.png)

Build log [https://pastebin.com/CQm9vXki](url)
Return codes is 7 and 8, folder c:\Temp is empty. STEAM and CS:GO installed

But little script on valve-python find url to dem file.

![изображение](https://user-images.githubusercontent.com/25701171/81525146-f642f600-937d-11ea-8e17-a637ccc74328.png)

With SDK version 1.46  and old version of code results is same.

**Comment by akiver** [comment]
The argument passed to the CLI must be a path to a file not a folder.
So instead of `boiler.exe "c:\temp"` it should be `boiler.exe "c:\temp\matches.info"` for example.

**Comment by PetroGolovnya** [comment]
Ok. I download binary file with link at end 
![изображение](https://user-images.githubusercontent.com/25701171/81538205-a160a900-9398-11ea-8ec5-d205cbc3d4b8.png)

I should copy link and download demo manually?

**Comment by akiver** [comment]
As mentioned in the readme, the CLI only writes the protobuf message into a file (your screenshot is the message serialized).
If you want to decode its data you will have to parse this file using the proto lib of your choice.

If you only want the demo URL, using a regex to find it may work.
