### ISSUE TITLE
run error shared object not found

### ISSUE THREAD

**Issue by Julien2313** [akiver/boiler-writter#3]
If I'm not adding libstream_api.so in the right directory (in example `/usr/lib`), it doesn't take the one in the same directory of the executable. `./boiler-writter: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

**Comment by adobito** [comment]
@Julien2313 Did you ever get it running? I'm running into the same issue.

**Comment by Julien2313** [comment]
Yes, I added libstream_api.so in /usr/lib ^^

**Comment by adobito** [comment]
so did you have `/usr/lib/libsteam_api.so`?

I managed to get it running on windows command line but not WSL yet, maybe it doesn't like WSL.

**Comment by akiver** [comment]
Hi!  
The linking error on Linux should be fixed in version [1.2.0.](https://github.com/akiver/boiler-writter/releases/tag/v1.2.0)
Feel free to reopen this issue if it's still not working on Linux 😃
