### ISSUE TITLE
How can I parse a .info file?

### ISSUE THREAD

**Issue by herzog0** [akiver/boiler-writter#6]
Hello again. 
Just a note on my last question (#5): I got a more recent share code and everything worked just fine :) 
I can now retrieve two files from boiler-writter, one of them being a xxxx.info file.  
Do you have any idea on which tools I could use to parse it? 
The demo file I know how to parse already, but I couldn't find anything for the info file. 

Thanks!

**Comment by akiver** [comment]
Hi,

`.info` files contain a [CDataGCCStrike15_v2_MatchInfo](https://github.com/SteamDatabase/Protobufs/blob/master/csgo/cstrike15_gcmessages.proto#L888) protobuf message.
You have to parse it to extract the data using the protobuf lib (the language is up to you).

1. Compile the [CSGO .proto files](https://github.com/SteamDatabase/Protobufs/tree/master/csgo) to generate protobuf classes using the compiler `protoc`
2. Parse the `.info` file using the previously generated classes to extract the `CDataGCCStrike15_v2_MatchInfo` message, here is a [C# example](https://github.com/akiver/cs-demo-manager/blob/v2/Services/Concrete/DemosService.cs#L429)
